### ISSUE TITLE
start optimization over RESTful API calls

### ISSUE THREAD

**Issue by cn-tools** [343dev/optimizt#4]
I'm using [paperless-ngx](https://github.com/paperless-ngx/paperless-ngx) inside the (docker) container station on my qnap nas.

I defined a folder "consume" in my "docker-compose.yaml" where paperless-ngx looks for new files. In addition i pass a docker variable named "[PAPERLESS_PRE_CONSUME_SCRIPT](https://docs.paperless-ngx.com/advanced_usage/#pre-consume-script)" to execute a special script before the new file will processed.

My wish:
If a new file is available, i would like to execute a script to check if the file is an image and if yes, i would like to optimize that image with "optimizt".

My idea:
1) I run a container of "optimizt"
3) Pass the right folders into both containers
2) In my "PAPERLESS_PRE_CONSUME_SCRIPT" script i would like to fire up a call, that the new file should be optimized.

As the two containers don't know anything about the other, it would be nice that i can execute a RESTful API call to fire up the optimization of the new image.

My question:
Is it possible to integrate a RESTful API interface?
Maybe with [Flask-Shell2HTTP](https://github.com/Eshaan7/Flask-Shell2HTTP)

**Comment by 343dev** [comment]
Hi there. I think it’s possible. However, this case is quite specific, so I don’t see the need to include it in Optimizt Docker image.

You can do it yourself and post the solution here. It might be useful for someone in the future.

I’m not sure about the limitations of Docker on NAS, but it might be easier to implement a scheme with a file watcher that automatically takes unoptimized images from the specified directory, optimizes them, and moves them to the directory for paperless-ngx.

You will need to create a **Dockerfile** that looks something like this:

```dockerfile
FROM node:18.17.0-bullseye-slim
LABEL maintainer="Andrey Warkentin (https://github.com/343dev)"

WORKDIR /app

ENV NODE_ENV="production"
ENV SHELL="/bin/bash"

RUN apt update \
  && apt install --yes --no-install-recommends build-essential libpng16-16 libjpeg62-turbo libjpeg62-turbo-dev libpng-dev pkg-config dh-autoreconf \
  && npm install --global @343dev/optimizt chokidar-cli \
  && npm cache clean --force \
  && apt purge --yes build-essential pkg-config libpng-dev libjpeg62-turbo-dev dh-autoreconf \
  && apt autoremove --yes --purge \
  && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

WORKDIR /src

CMD chokidar "/src/input/**/*" \
  --command "if [ '{event}' = 'add' ]; then optimizt --verbose /src/input && mv /src/input/* /src/output; fi;" \
  --polling
```

Then create an image from it using the command:

```sh
docker build --tag 343dev/optimizt-watcher .
```

And start the container with the command:

```sh
docker run \
  --detach \
  --restart unless-stopped \
  --volume /your/input:/src/input \
  --volume /your/output:/src/output \
  --name optimizt-watcher \
  343dev/optimizt-watcher
```

After that, all files placed in the directory “/your/input” will be automatically optimized and moved to the directory “/your/output”.
